/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBO.Department;
import DBO.Stu_Dep;
import DBO.Student;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }
    public Home(Locale Start){
        Locale.setDefault(Start);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    void refreshTable(List stList){
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, stList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sid}"));
        columnBinding.setColumnName("Sid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${age}"));
        columnBinding.setColumnName("Age");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${did}"));
        columnBinding.setColumnName("Did");
        columnBinding.setColumnClass(DBO.Department.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        StudentSystemDCBSDPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory(bundle.getString("Home.StudentSystemDCBSDPUEntityManager.persistenceUnit")).createEntityManager(); // NOI18N
        studentQuery = java.beans.Beans.isDesignTime() ? null : StudentSystemDCBSDPUEntityManager.createQuery(bundle.getString("Home.studentQuery.query")); // NOI18N
        studentList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentQuery.getResultList();
        departmentQuery = java.beans.Beans.isDesignTime() ? null : StudentSystemDCBSDPUEntityManager.createQuery(bundle.getString("Home.departmentQuery.query")); // NOI18N
        departmentList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : departmentQuery.getResultList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SIDLbl = new javax.swing.JLabel();
        SIDtxt = new javax.swing.JTextField();
        SnameLbl = new javax.swing.JLabel();
        Snametxt = new javax.swing.JTextField();
        SageLbl = new javax.swing.JLabel();
        Agetxt = new javax.swing.JTextField();
        adresstxt = new javax.swing.JTextField();
        SaddressLbl = new javax.swing.JLabel();
        DepLbl = new javax.swing.JLabel();
        DepartmntCMB = new javax.swing.JComboBox();
        InsertBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        DepSumBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IDRDBTN = new javax.swing.JRadioButton();
        NameRBTN = new javax.swing.JRadioButton();
        AddressRBTN = new javax.swing.JRadioButton();
        searchtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SIDLbl.setText(bundle.getString("Home.SIDLbl.text")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.sid}"), SIDtxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIDtxtActionPerformed(evt);
            }
        });

        SnameLbl.setText(bundle.getString("Home.SnameLbl.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.name}"), Snametxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SageLbl.setText(bundle.getString("Home.SageLbl.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.age}"), Agetxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.address}"), adresstxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SaddressLbl.setText(bundle.getString("Home.SaddressLbl.text")); // NOI18N

        DepLbl.setText(bundle.getString("Home.DepLbl.text")); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, departmentList, DepartmntCMB);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.did}"), DepartmntCMB, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        InsertBTN.setText(bundle.getString("Home.InsertBTN.text")); // NOI18N
        InsertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setText(bundle.getString("Home.DeleteBTN.text")); // NOI18N
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setText(bundle.getString("Home.UpdateBTN.text")); // NOI18N
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        DepSumBTN.setText(bundle.getString("Home.DepSumBTN.text")); // NOI18N
        DepSumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepSumBTNActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, studentList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sid}"));
        columnBinding.setColumnName("Sid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${age}"));
        columnBinding.setColumnName("Age");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${did}"));
        columnBinding.setColumnName("Did");
        columnBinding.setColumnClass(DBO.Department.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(IDRDBTN);
        IDRDBTN.setText(bundle.getString("Home.IDRDBTN.text")); // NOI18N

        buttonGroup1.add(NameRBTN);
        NameRBTN.setText(bundle.getString("Home.NameRBTN.text")); // NOI18N

        buttonGroup1.add(AddressRBTN);
        AddressRBTN.setText(bundle.getString("Home.AddressRBTN.text")); // NOI18N

        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DepLbl)
                                .addComponent(SIDLbl)
                                .addComponent(SnameLbl)
                                .addComponent(SageLbl)
                                .addComponent(SaddressLbl)
                                .addComponent(InsertBTN))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DeleteBTN)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DepartmntCMB, 0, 94, Short.MAX_VALUE)
                                    .addComponent(SIDtxt)
                                    .addComponent(Snametxt)
                                    .addComponent(Agetxt)
                                    .addComponent(adresstxt))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DepSumBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(UpdateBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(68, 68, 68)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(IDRDBTN)
                                    .addGap(47, 47, 47)
                                    .addComponent(NameRBTN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddressRBTN))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SIDLbl)
                        .addComponent(SIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SnameLbl)
                                .addComponent(Snametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IDRDBTN)
                                .addComponent(NameRBTN)
                                .addComponent(AddressRBTN))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SageLbl)
                                .addComponent(Agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaddressLbl)
                                .addComponent(adresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DepLbl)
                                .addComponent(DepartmntCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(InsertBTN)
                                .addComponent(DeleteBTN))
                            .addGap(18, 18, 18)
                            .addComponent(UpdateBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DepSumBTN)))
                    .addGap(40, 40, 40)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBTNActionPerformed
                Student s = new Student();
                s.setSid(SIDtxt.getText());
                s.setName(Snametxt.getText());
                s.setAge(Integer.parseInt(Agetxt.getText()));
                s.setAddress(adresstxt.getText());
                s.setDid((Department)DepartmntCMB.getSelectedItem());
        
                int res=JOptionPane.showConfirmDialog(this, s.getSid(), "insert ?", 1);
                if(res==JOptionPane.OK_OPTION){
                    try {
                        StudentSystemDCBSDPUEntityManager.getTransaction().begin();
                        StudentSystemDCBSDPUEntityManager.persist(s);
                        StudentSystemDCBSDPUEntityManager.getTransaction().commit();
                        JOptionPane.showConfirmDialog(this, s.getSid()+"Insert ?");
                    } catch (Exception e) {
                        System.out.println("Found Duplicate SID!!!");
                       JOptionPane.showMessageDialog(this, "Please Provide defferent Student ID from existings");
                    }
                       
                       
                    }
                studentList.clear();
                studentList=studentQuery.getResultList();
                refreshTable(studentList);
    }//GEN-LAST:event_InsertBTNActionPerformed

    private void SIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIDtxtActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        Student s = StudentSystemDCBSDPUEntityManager.find(Student.class, SIDtxt.getText());
        
        int res=JOptionPane.showConfirmDialog(this, s.getSid(), "Delete ?", 1);
                if(res==JOptionPane.OK_OPTION){
                        StudentSystemDCBSDPUEntityManager.getTransaction().begin();
                        StudentSystemDCBSDPUEntityManager.remove(s);
                        StudentSystemDCBSDPUEntityManager.getTransaction().commit();
                        JOptionPane.showConfirmDialog(this, s.getSid()+"Delete?");
                }
                studentList.clear();
                studentList=studentQuery.getResultList();
                refreshTable(studentList);
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        Student s = StudentSystemDCBSDPUEntityManager.find(Student.class, SIDtxt.getText());
        
        s.setName(Snametxt.getText());
                s.setAge(Integer.parseInt(Agetxt.getText()));
                s.setAddress(adresstxt.getText());
                s.setDid((Department)DepartmntCMB.getSelectedItem());
        
                int res=JOptionPane.showConfirmDialog(this, s.getSid(), "Update ?", 1);
                if(res==JOptionPane.OK_OPTION){
                        StudentSystemDCBSDPUEntityManager.getTransaction().begin();
                        StudentSystemDCBSDPUEntityManager.merge(s);
                        StudentSystemDCBSDPUEntityManager.getTransaction().commit();
                        JOptionPane.showConfirmDialog(this, s.getSid()+"Update?");
                    
                       
                    }
                studentList.clear();
                studentList=studentQuery.getResultList();
                refreshTable(studentList);
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        if(IDRDBTN.isSelected()){
            Query qid = StudentSystemDCBSDPUEntityManager.createQuery("SELECT s FROM Student s WHERE s.sid like :sid");
            qid.setParameter("sid", "%"+searchtxt.getText()+"%");
            
            studentList.clear();
            studentList = qid.getResultList();
            refreshTable(studentList);
        }
        else if(NameRBTN.isSelected()){
            Query qname = StudentSystemDCBSDPUEntityManager.createQuery("SELECT s FROM Student s WHERE s.name like :name");
            qname.setParameter("name", "%"+searchtxt.getText()+"%");
            
            studentList.clear();
            studentList = qname.getResultList();
            refreshTable(studentList);
        }
        else if(AddressRBTN.isSelected()){
            Query qadd = StudentSystemDCBSDPUEntityManager.createQuery("SELECT s FROM Student s WHERE s.address like :address");
            qadd.setParameter("address", "%"+searchtxt.getText()+"%");
            
            studentList.clear();
            studentList = qadd.getResultList();
            refreshTable(studentList);
        }
        else{
            JOptionPane.showMessageDialog(this, "Select a Search Critaria!");
        }
    }//GEN-LAST:event_searchtxtKeyReleased

    private void DepSumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepSumBTNActionPerformed
        List<Stu_Dep> depSum = new ArrayList<>();
        depSum.add(new Stu_Dep(0, "MM"));
        depSum.add(new Stu_Dep(0, "HR"));
        depSum.add(new Stu_Dep(0, "IT"));
        
        for (Student st : studentList) {
            switch(st.getDid().getDepartmentName())
            {
                case "MM" : depSum.get(0).setCount(depSum.get(0).getCount()+1);break;
                case "HR" : depSum.get(1).setCount(depSum.get(1).getCount()+1);break;
                case "IT" : depSum.get(2).setCount(depSum.get(2).getCount()+1);break;
                default:break;
            }
        }
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, depSum, jTable3);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${depName}"));
        columnBinding.setColumnName("Department Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${count}"));
        columnBinding.setColumnName("Number OF Students");
        columnBinding.setColumnClass(Integer.class);
        
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
    }//GEN-LAST:event_DepSumBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddressRBTN;
    private javax.swing.JTextField Agetxt;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JLabel DepLbl;
    private javax.swing.JButton DepSumBTN;
    private javax.swing.JComboBox DepartmntCMB;
    private javax.swing.JRadioButton IDRDBTN;
    private javax.swing.JButton InsertBTN;
    private javax.swing.JRadioButton NameRBTN;
    private javax.swing.JLabel SIDLbl;
    private javax.swing.JTextField SIDtxt;
    private javax.swing.JLabel SaddressLbl;
    private javax.swing.JLabel SageLbl;
    private javax.swing.JLabel SnameLbl;
    private javax.swing.JTextField Snametxt;
    private javax.persistence.EntityManager StudentSystemDCBSDPUEntityManager;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JTextField adresstxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.util.List<DBO.Department> departmentList;
    private javax.persistence.Query departmentQuery;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField searchtxt;
    private java.util.List<DBO.Student> studentList;
    private javax.persistence.Query studentQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
